"""Alembic env.py for Metaxy feature tables on DuckLake (DuckDB 1.5+).

DuckLake is an OLAP lakehouse format. Like many OLAP systems, it does not
support PRIMARY KEY, UNIQUE, or RETURNING (see
https://ducklake.select/docs/stable/duckdb/advanced_features/constraints).

This env.py adapts Alembic:

- Constraints are stripped from the target metadata.
- ``version_table_pk=False`` creates alembic_version without a primary key.
- ``insert_returning`` is disabled on the dialect.
- DuckLake partitioning and sorted-table DDL is emitted after each
  ``create_table`` via an ``AlembicDuckDBImpl.create_table()`` override.
- A monkey-patch on ``_columns_query`` replaces the ``pg_collation``
  subquery with NULL so column reflection works on DuckDB 1.5
  (upstream: https://github.com/Mause/duckdb_engine/issues/1391).

The patches in this file target duckdb-engine 0.17.x, alembic 1.17.x, and
DuckDB 1.5.x (pinned in pyproject.toml). Other versions may require adjustments.
"""

from functools import lru_cache

import metaxy as mx
from alembic.ddl.impl import DefaultImpl
from duckdb_engine import Dialect as DuckDBDialect  # ty: ignore[unresolved-import]
from metaxy.ext.metadata_stores.duckdb import DuckDBMetadataStore
from metaxy.ext.sqlmodel import filter_feature_sqlmodel_metadata
from sqlalchemy import JSON, PrimaryKeyConstraint, UniqueConstraint, null
from sqlalchemy.types import UserDefinedType
from sqlmodel import SQLModel


class VARIANT(UserDefinedType):
    """DuckDB 1.5 VARIANT type for semi-structured data."""

    cache_ok = True

    def get_col_spec(self, **kw):
        return "VARIANT"


import example_alembic.definitions  # noqa: F401  # ty: ignore[unresolved-import]
from alembic import context

# ---------------------------------------------------------------------------
# Monkey-patch duckdb-engine: replace the pg_collation subquery with NULL.
# DuckDB 1.5 removed pg_collation from pg_catalog.
# ---------------------------------------------------------------------------
_orig_columns_query = DuckDBDialect._columns_query.__wrapped__


@lru_cache
def _patched_columns_query(self, schema, has_filter_names, scope, kind):
    query = _orig_columns_query(self, schema, has_filter_names, scope, kind)
    new_columns = [
        null().label("collation") if col.key == "collation" else col
        for col in query.selected_columns
    ]
    return query.with_only_columns(*new_columns)


DuckDBDialect._columns_query = _patched_columns_query


# ---------------------------------------------------------------------------
# DuckLake DDL implementation for Alembic
# ---------------------------------------------------------------------------

# Per-table DuckLake DDL: partitioning and sorting applied after create_table.
_DUCKLAKE_TABLE_DDL: dict[str, list[str]] = {
    "examples__alembic_demo": [
        "ALTER TABLE examples__alembic_demo SET PARTITIONED BY (metaxy_feature_version)",
        "ALTER TABLE examples__alembic_demo SET SORTED BY (metaxy_updated_at)",
    ],
}


class AlembicDuckDBImpl(DefaultImpl):
    """Alembic DDL for DuckDB/DuckLake.

    Disables RETURNING (unsupported by DuckLake) and emits DuckLake-specific
    DDL (partitioning, sorting) after each table creation.
    """

    __dialect__ = "duckdb"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.dialect.insert_returning = False
        self.dialect.update_returning = False

    def create_table(self, table, **kw):
        super().create_table(table, **kw)
        for stmt in _DUCKLAKE_TABLE_DDL.get(table.name, []):
            self.execute(stmt)


# ---------------------------------------------------------------------------
# Metaxy init + metadata
# ---------------------------------------------------------------------------
metaxy_cfg = mx.init()
store = metaxy_cfg.get_store("dev")
assert isinstance(store, DuckDBMetadataStore)

url, target_metadata = filter_feature_sqlmodel_metadata(store, SQLModel.metadata)
_ducklake_init_sql = store.ducklake_attachment.preview_sql()

# Adapt metadata for DuckLake: strip constraints and promote JSON to VARIANT.
for table in target_metadata.tables.values():
    table.constraints = {
        c
        for c in table.constraints
        if not isinstance(c, (PrimaryKeyConstraint, UniqueConstraint))
    }
    for col in table.columns:
        col.primary_key = False
        if isinstance(col.type, JSON):
            col.type = VARIANT()


def _include_name(name, type_, _parent_names):
    """Exclude DuckLake internal catalog tables from reflection."""
    if type_ == "table":
        return not name.startswith("ducklake_")
    return True


def _render_item(type_, obj, autogen_context):
    """Render VARIANT() instead of env_py.VARIANT() in autogenerated migrations."""
    if (
        type_ == "type"
        and hasattr(obj, "get_col_spec")
        and obj.get_col_spec() == "VARIANT"
    ):
        return "VARIANT()"
    return False


def run_migrations_offline() -> None:
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_name=_include_name,
        version_table_pk=False,
        render_item=_render_item,
        user_module_prefix="",
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    from sqlalchemy import create_engine, event

    engine = create_engine(url)

    @event.listens_for(engine, "connect")
    def _init_ducklake(dbapi_conn, _connection_record):
        cursor = dbapi_conn.cursor()
        for stmt in _ducklake_init_sql:
            cursor.execute(stmt)
        cursor.close()

    with engine.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_name=_include_name,
            version_table_pk=False,
            render_item=_render_item,
            # user_module_prefix left as default so sqlmodel types render correctly
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
