interfaces = []
exclude = [
  "**/*__pycache__",
  "**/*egg-info",
  "**/docs",
  "**/tests",
  "**/venv",
]
source_roots = ["src"]

[[modules]]
path = "metaxy.entrypoints"
depends_on = ["metaxy.models"]

[[modules]]
path = "metaxy.ext.dagster"
depends_on = ["metaxy.models", "metaxy.metadata_store", "metaxy"]

[[modules]]
path = "metaxy._hashing"
depends_on = ["metaxy"]
utility = true

[[modules]]
path = "metaxy._warnings"
depends_on = []
utility = true

[[modules]]
path = "metaxy.models"
depends_on = ["metaxy.config"]

[[modules]]
path = "metaxy.ext.sqlalchemy"
depends_on = ["metaxy.config", "metaxy.models", "metaxy.metadata_store"]

[[modules]]
path = "metaxy.ext.sqlmodel"
depends_on = ["metaxy.ext.sqlalchemy", "metaxy.models", "metaxy.config", "metaxy"]

[[modules]]
path = "metaxy.versioning"
depends_on = ["metaxy.config", "metaxy.models"]
utility = true

[[modules]]
path = "metaxy._exceptions"
depends_on = []
utility = true

[[modules]]
path = "metaxy.metadata_store"
depends_on = ["metaxy.models", "metaxy.config", "metaxy"]

[[modules]]
path = "metaxy.cli"
depends_on = ["metaxy.ext.mcp", "metaxy.models", "metaxy.metadata_store", "metaxy.config", "metaxy"]

[[modules]]
path = "metaxy.utils"
depends_on = ["metaxy.config", "metaxy.metadata_store", "metaxy.models", "metaxy"]
utility = true

[[modules]]
path = "metaxy.ext.ray"
depends_on = ["metaxy"]

[[modules]]
path = "metaxy.ext.mcp"
depends_on = ["metaxy.models", "metaxy"]

[[modules]]
path = "metaxy.config"
depends_on = ["metaxy.models"]

[[modules]]
path = "metaxy._version"
depends_on = []
utility = true

[[modules]]
path = "metaxy._packaging"
depends_on = []
utility = true

[[modules]]
path = "metaxy.graph"
depends_on = ["metaxy.metadata_store", "metaxy.models"]
utility = true

[[modules]]
path = "metaxy._decorators"
depends_on = []
utility = true

[[modules]]
path = "metaxy"
depends_on = [
  "metaxy.metadata_store",
  "metaxy.entrypoints",
  "metaxy.config",
  "metaxy.models",
  "metaxy.ext.polars.handlers.iceberg",
  "metaxy.ext.duckdb",
  "metaxy.ext.polars.handlers.delta",
  "metaxy.ext.bigquery",
  "metaxy.ext.clickhouse",
  "metaxy.ext.lancedb",
  "metaxy.ext.postgresql",
]

[[modules]]
path = "metaxy.ext.bigquery"
depends_on = ["metaxy.metadata_store"]

[[modules]]
path = "metaxy.ext.polars.handlers.delta"
depends_on = ["metaxy.config", "metaxy.metadata_store", "metaxy.models"]

[[modules]]
path = "metaxy.ext.duckdb"
depends_on = ["metaxy.config", "metaxy.metadata_store"]

[[modules]]
path = "metaxy.ext.polars"
depends_on = ["metaxy.ext.polars.handlers.iceberg", "metaxy.ext.polars.handlers.delta"]

[[modules]]
path = "metaxy.ext.polars.handlers.iceberg"
depends_on = ["metaxy.metadata_store", "metaxy.config", "metaxy.models"]

[[modules]]
path = "metaxy.ext.clickhouse"
depends_on = ["metaxy.metadata_store", "metaxy.config", "metaxy.models"]

[[modules]]
path = "metaxy.ext.postgresql"
depends_on = ["metaxy.models", "metaxy.metadata_store"]

[[modules]]
path = "metaxy.ext.lancedb"
depends_on = ["metaxy.metadata_store", "metaxy.models"]
