name: "Quickstart Example"
description: "Demonstrates root and downstream feature resolution with resolve_update"
package_name: "example_quickstart"

scenarios:
  - name: "Initial pipeline run"
    description: "First execution resolves all samples as new"
    steps:
      - name: "initial_run"
        type: "run_command"
        command: "python -m example_quickstart.pipeline"
        description: "Run pipeline with initial feature definitions"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify pipeline completed with new samples"
        returncode: 0
        contains:
          - "Quickstart Pipeline"
          - "[Video]"
          - "[Audio]"
          - "✅ Pipeline complete!"

  - name: "Idempotent rerun"
    description: "Second execution should detect no changes"
    steps:
      - name: "idempotent_run"
        type: "run_command"
        command: "python -m example_quickstart.pipeline"
        description: "Rerun pipeline without any changes"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify idempotence (no recomputation)"
        returncode: 0
        contains:
          - "No changes detected (idempotent)"
