name: Setup Devenv
description: Install Nix, devenv, direnv and activate the development environment

inputs:
  install-deps:
    description: Whether to run uv sync
    required: false
    default: "true"

runs:
  using: composite
  steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: devenv

    - name: Setup Magic Nix Cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Install devenv
      shell: bash
      run: nix profile install nixpkgs#devenv nixpkgs#direnv

    - name: Activate devenv environment
      shell: bash
      env:
        # Allow builtins.getEnv for DEVENV_PYTHON_VERSION
        DEVENV_NIX_FLAGS: "--impure"
      run: |
        direnv allow .
        direnv export gha >> "$GITHUB_ENV"

    - name: Install Python dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: uv sync --all-extras --all-groups
