entrypoints = ["examples.ducklake.demo"]

[stores.dev]
type = "metaxy.metadata_store.duckdb.DuckDBMetadataStore"

[stores.dev.config]
database = ":memory:"

[stores.dev.config.ducklake.attach_options]
api_version = "0.2"
override_data_path = true

[stores.dev.config.ducklake.metadata_backend]
type = "postgres"
database = "ducklake_meta"
user = "ducklake"
password = "secret"

[stores.dev.config.ducklake.storage_backend]
type = "s3"
endpoint_url = "https://object-store"
bucket = "ducklake"
prefix = "metadata"
aws_access_key_id = "key"
aws_secret_access_key = "secret"
