project = "examples"
entrypoints = ["examples.ducklake.demo"]
auto_create_tables = true # Enable for development/examples

[stores.dev]
type = "metaxy.metadata_store.duckdb.DuckDBMetadataStore"

[stores.dev.config]
database = "/tmp/ducklake_demo.db"

[stores.dev.config.ducklake.attach_options]
override_data_path = true

[stores.dev.config.ducklake.metadata_backend]
type = "sqlite"
path = "/tmp/ducklake_meta.db"

[stores.dev.config.ducklake.storage_backend]
type = "local"
path = "/tmp/ducklake_storage"
