name: "One-to-Many Expansion Example"
description: "Demonstrates 1:N expansion relationships and field-level provenance tracking"
package_name: "example_one_to_many"

scenarios:
  - name: "Initial pipeline run"
    description: "First execution creates videos, chunks, and face recognition"
    steps:
      - type: "run_command"
        command: "python pipeline.py"
        description: "Run pipeline to create videos, chunks, and face recognition"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify pipeline processed all features"
        returncode: 0
        contains:
          - "Found 3 new videos"
          - "Found 3 videos and 0 videos that need chunking"
          - "Writing"
          - "chunks for video"
          - "video chunks and 0 video chunks that need face recognition"
          - "Writing face recognition"

  - name: "Idempotent rerun"
    description: "Second execution should detect no changes"
    steps:
      - type: "run_command"
        command: "python pipeline.py"
        description: "Rerun pipeline without any code changes"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify nothing needs recomputation (idempotent)"
        returncode: 0
        contains:
          - "Found 0 videos and 0 videos that need chunking"
          - "Found 0 video chunks and 0 video chunks that need face recognition"

  - name: "Code change - audio field only"
    description: "Apply patch to change Video audio code_version, observe field-level tracking"
    steps:
      - type: "apply_patch"
        patch_path: "patches/01_update_video_code_version.patch"
        description: "Change Video audio field code_version from 1 to 2"

      - type: "run_command"
        command: "python pipeline.py"
        description: "Run pipeline after audio code_version change"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify VideoChunks recompute but FaceRecognition does NOT (field-level tracking)"
        returncode: 0
        contains:
          - "Found 3 videos and 0 videos that need chunking"
          - "video chunks and 0 video chunks that need face recognition"
          - "Writing"
          - "chunks for video"

  - name: "Final idempotent check"
    description: "Verify no further recomputation needed after code change processed"
    steps:
      - type: "run_command"
        command: "python pipeline.py"
        description: "Rerun pipeline after code change"
        capture_output: true
        timeout: 30.0

      - type: "assert_output"
        description: "Verify everything is up-to-date"
        returncode: 0
        contains:
          - "Found 0 videos and 0 videos that need chunking"
          - "Found 0 video chunks and 0 video chunks that need face recognition"
