DAGSTER_METAXY_FEATURE_METADATA_KEY = "metaxy/feature"
DAGSTER_METAXY_METADATA_METADATA_KEY = "metaxy/metadata"
DAGSTER_METAXY_KIND = "metaxy"
DAGSTER_METAXY_PARTITION_KEY = "partition_by"

METAXY_DAGSTER_METADATA_KEY = "metaxy/dagster"
